repo:
  - ./*
examples:
  - examples/**/*
charts:
  - charts/**/*
eap-xp6:
  - charts/eap-xp6/**/*
  - examples/eap-xp6/**/*
documentation:
  - ./README.md
  - charts/**/README.md
  - charts/**/values.schema.json
 
