{{- if .Values.deploy.enabled }}
{{- include "wildfly-common.deployment" (list . "eap-xp4.deployment") -}}
{{- end -}}

{{ define "eap-xp4.deployment" }}
{{- include "eap-xp4.metadata.labels" . }}
spec:
  template:
    {{- include "eap-xp4.metadata.labels" . | nindent 4 }}
{{- end -}}