# Default values for JBoss EAP XP 6
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: latest
build:
  enabled: true
  uri: https://github.com/jboss-eap-up-and-running/eap-xp6-getting-started.git
  mode: bootable-jar
  bootableJar:
    builderImage: registry.access.redhat.com/ubi8/openjdk-17:latest
  s2i:
    buildApplicationImage: true
    kind: DockerImage
    jdk: "17"
    jdk17:
      builderImage: registry.redhat.io/jboss-eap-8-tech-preview/eap81-openjdk17-builder-openshift-rhel9:latest
      runtimeImage: registry.redhat.io/jboss-eap-8-tech-preview/eap81-openjdk17-runtime-openshift-rhel9:latest
  output:
    kind: "ImageStreamTag"
  triggers: {}
deploy:
  enabled: true
  replicas: 1
  tls: {}
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 60
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
    initialDelaySeconds: 10
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 60